# Generated by Django 4.0.5 on 2022-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='foo@gmail.com')),
                ('phone_no', models.IntegerField()),
                ('dob', models.DateField(verbose_name='%d-%m-%Y')),
                ('password', models.IntegerField()),
                ('cnic', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
